# Generated by Django 3.1.5 on 2021-07-28 10:13

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShapefileZip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('filename', models.CharField(max_length=255)),
                ('srs_wkt', models.CharField(max_length=255)),
                ('geom_type', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='multiPolygonFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medata', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict, null=True)),
                ('geo', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('shapefile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shape.shapefilezip')),
            ],
        ),
        migrations.CreateModel(
            name='multiPointFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medata', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict, null=True)),
                ('geo', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('shapefile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shape.shapefilezip')),
            ],
        ),
        migrations.CreateModel(
            name='multiLinestringFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medata', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict, null=True)),
                ('geo', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('shapefile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shape.shapefilezip')),
            ],
        ),
    ]
