# Generated by Django 3.1.5 on 2021-08-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shape', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapefilezip',
            name='file',
            field=models.FileField(upload_to='shp'),
        ),
    ]
